name: CaptureThis
options:
  deploymentTarget:
    macOS: "15.0"
  bundleIdPrefix: com.capturethis

packages:
  HotKey:
    url: https://github.com/soffes/HotKey
    from: 0.2.0

settings:
  base:
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1

targets:
  CaptureThis:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    resources:
      - path: Resources
    info:
      path: Config/Info.plist
      properties:
        LSUIElement: true
        NSCameraUsageDescription: CaptureThis uses the camera for picture-in-picture recording.
        NSMicrophoneUsageDescription: CaptureThis uses the microphone to record your voice.
        NSScreenCaptureUsageDescription: CaptureThis records your screen to create videos.
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.capturethis.CaptureThis
        CODE_SIGN_ENTITLEMENTS: Config/CaptureThis.entitlements
    dependencies:
      - package: HotKey
  CaptureThisTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests
    dependencies:
      - target: CaptureThis
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.capturethis.CaptureThisTests

schemes:
  CaptureThis:
    build:
      targets:
        CaptureThis: all
    test:
      targets:
        - CaptureThisTests
